import json

from masters_data import masters_data

def generate_html():
    html = []
    html.append('    <!-- ÁRBOL GENEALÓGICO & LÍNEA DE TIEMPO INTERACTIVA DE MAESTROS SHAOLIN -->')
    html.append('    <section id="arbol-maestros" class="w-full max-w-6xl mx-auto my-12" aria-label="Árbol Genealógico y Línea de Tiempo de Maestros Shaolin">')
    html.append('      ')
    html.append('      <!-- CONTENEDOR PRINCIPAL DEL ÁRBOL & CONTROLES -->')
    html.append('      <div class="bg-surface-container-lowest p-6 sm:p-8 rounded-3xl border border-surface-container-high shadow-xs mb-8">')
    html.append('        <div class="flex flex-col md:flex-row md:items-end justify-between gap-6 pb-6 border-b border-surface-container">')
    html.append('          <div>')
    html.append('            <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-50 border border-amber-200/80 text-ochre-deep text-xs font-semibold uppercase tracking-wider mb-2">')
    html.append('              <span class="w-2 h-2 rounded-full bg-ochre-gold animate-pulse"></span>')
    html.append('              <span>Linaje Ancestral • Templo Shaolin de Songshan</span>')
    html.append('            </div>')
    html.append('            <h2 class="text-2xl sm:text-3xl lg:text-4xl font-extrabold font-display text-on-surface tracking-tight">')
    html.append('              Árbol Genealógico &amp; Transmisión Marcial')
    html.append('            </h2>')
    html.append('            <p class="mt-2 text-xs sm:text-sm text-secondary font-body max-w-2xl">')
    html.append('              Pasa el cursor por cada maestro del árbol o de la línea temporal para activar su información, historia, rol doctrinal y linaje.')
    html.append('            </p>')
    html.append('          </div>')
    html.append('')
    html.append('          <!-- Contador Dinámico y Botones de Control -->')
    html.append('          <div class="flex items-center gap-3 shrink-0">')
    html.append('            <div class="px-4 py-2 rounded-xl bg-surface-container border border-surface-container-high text-xs font-bold text-on-surface flex items-center gap-2 shadow-xs">')
    html.append('              <span class="w-2 h-2 rounded-full bg-primary"></span>')
    html.append('              <span id="lineage-counter" class="font-mono text-primary font-bold">01 / 08</span>')
    html.append('              <span class="text-stone-300">|</span>')
    html.append('              <span id="lineage-name-label" class="text-secondary font-medium truncate max-w-[140px] sm:max-w-[200px]">Shi Suxi Zhang Lao</span>')
    html.append('            </div>')
    html.append('            <div class="flex items-center gap-1.5">')
    html.append('              <button type="button" id="lineage-prev-btn" class="p-2 sm:p-2.5 rounded-full bg-white border border-stone-200 text-stone-700 hover:text-primary hover:border-primary hover:bg-stone-50 transition-all shadow-xs flex items-center justify-center cursor-pointer" aria-label="Maestro anterior">')
    html.append('                <span class="material-symbols-outlined text-lg">chevron_left</span>')
    html.append('              </button>')
    html.append('              <button type="button" id="lineage-next-btn" class="p-2 sm:p-2.5 rounded-full bg-white border border-stone-200 text-stone-700 hover:text-primary hover:border-primary hover:bg-stone-50 transition-all shadow-xs flex items-center justify-center cursor-pointer" aria-label="Siguiente maestro">')
    html.append('                <span class="material-symbols-outlined text-lg">chevron_right</span>')
    html.append('              </button>')
    html.append('            </div>')
    html.append('          </div>')
    html.append('        </div>')
    html.append('')
    html.append('        <!-- 1. LÍNEA DE TIEMPO INTERACTIVA (TIMELINE NAVIGATOR) -->')
    html.append('        <div class="pt-6">')
    html.append('          <div class="text-[11px] uppercase tracking-wider font-bold text-stone-500 mb-3 flex items-center justify-between">')
    html.append('            <span class="flex items-center gap-1.5">')
    html.append('              <span class="material-symbols-outlined text-ochre-gold text-sm">timeline</span>')
    html.append('              Línea de Tiempo Cronológica (Pasa el cursor por cada maestro):')
    html.append('            </span>')
    html.append('            <span class="text-ochre-deep font-semibold hidden md:inline">30ª Gen ➔ 31ª Gen ➔ 32ª Gen ➔ Instructores &amp; Sedes</span>')
    html.append('          </div>')
    html.append('')
    html.append('          <div class="lineage-timeline-track flex items-center gap-2 sm:gap-3 py-2 px-1 overflow-x-auto no-scrollbar" role="tablist">')
    
    for idx, m in enumerate(masters_data):
        active_cls = "active" if idx == 0 else ""
        html.append(f'            <!-- Step {m["index"]}: {m["short_name"]} -->')
        html.append(f'            <button type="button" class="tree-node-master {active_cls} group shrink-0 p-2 sm:p-2.5 rounded-2xl bg-white border border-stone-200 hover:border-ochre-gold text-left flex items-center gap-2.5 transition-all shadow-xs cursor-pointer focus:outline-none" data-master-idx="{idx}" role="tab" aria-selected="{"true" if idx == 0 else "false"}" aria-controls="{m["id"]}">')
        html.append(f'              <div class="w-10 h-10 sm:w-11 sm:h-11 rounded-xl overflow-hidden bg-stone-100 border-2 border-stone-200 group-hover:border-ochre-gold transition-colors shrink-0 node-avatar-ring relative">')
        html.append(f'                <img src="{m["photo"]}" alt="{m["name"]}" class="w-full h-full object-cover">')
        html.append(f'              </div>')
        html.append(f'              <div class="flex flex-col pr-1">')
        html.append(f'                <span class="text-[9px] font-bold uppercase tracking-wider text-ochre-deep leading-none mb-0.5">{m["tier"]}</span>')
        html.append(f'                <span class="text-xs font-bold text-stone-900 group-hover:text-primary transition-colors whitespace-nowrap leading-tight">{m["short_name"]}</span>')
        html.append(f'              </div>')
        html.append(f'              <span class="w-1.5 h-1.5 rounded-full bg-primary ml-1 node-active-pill transition-all"></span>')
        html.append(f'            </button>')
        if idx < len(masters_data) - 1:
            html.append('            <span class="text-stone-300 shrink-0 font-light select-none">→</span>')

    html.append('          </div>')
    html.append('        </div>')
    html.append('')
    html.append('        <!-- 2. ÁRBOL GENEALÓGICO VISUAL (RAMIFICACIÓN MARCIAL) -->')
    html.append('        <div class="mt-8 pt-6 border-t border-surface-container">')
    html.append('          <div class="text-[11px] uppercase tracking-wider font-bold text-stone-500 mb-6 flex items-center gap-2">')
    html.append('            <span class="material-symbols-outlined text-ochre-gold text-base">account_tree</span>')
    html.append('            <span>Estructura Visual del Árbol de Transmisión (Hover interactivo):</span>')
    html.append('          </div>')
    html.append('')
    html.append('          <div class="flex flex-col items-center w-full">')
    html.append('            <!-- NIVEL 1: 30ª Generación (Raíz de Songshan) -->')
    html.append('            <div class="flex flex-col items-center">')
    html.append('              <div class="text-[10px] font-bold uppercase tracking-widest text-ochre-deep bg-amber-50 border border-amber-200 px-3 py-0.5 rounded-full mb-2">30ª Generación • Monte Songshan</div>')
    html.append('              <button type="button" class="tree-node-master active group p-3 sm:p-3.5 rounded-2xl bg-white border border-stone-200 hover:border-ochre-gold flex items-center gap-3 transition-all shadow-xs cursor-pointer text-left" data-master-idx="0">')
    html.append('                <div class="w-12 h-12 rounded-xl overflow-hidden border-2 border-stone-200 group-hover:border-ochre-gold node-avatar-ring shrink-0">')
    html.append('                  <img src="imagenes/m_Dai-Shifu-Suxi-12.jpg" alt="Shi Suxi" class="w-full h-full object-cover">')
    html.append('                </div>')
    html.append('                <div>')
    html.append('                  <div class="text-xs font-bold text-stone-900 group-hover:text-primary transition-colors">Venerable Dai Shifu Shì Sùxǐ</div>')
    html.append('                  <div class="text-[11px] font-mono text-stone-500">1924–2006 • Líder Espiritual</div>')
    html.append('                </div>')
    html.append('                <span class="w-2 h-2 rounded-full bg-primary node-active-pill"></span>')
    html.append('              </button>')
    html.append('            </div>')
    html.append('')
    html.append('            <!-- Conector hacia Nivel 2 -->')
    html.append('            <div class="w-px h-8 bg-gradient-to-b from-ochre-gold to-primary my-1"></div>')
    html.append('')
    html.append('            <!-- NIVEL 2: 31ª Generación (Transmisión Monacal Directa) -->')
    html.append('            <div class="flex flex-col items-center">')
    html.append('              <div class="text-[10px] font-bold uppercase tracking-widest text-ochre-deep bg-amber-50 border border-amber-200 px-3 py-0.5 rounded-full mb-2">31ª Generación • Templo Shaolin</div>')
    html.append('              <button type="button" class="tree-node-master group p-3 sm:p-3.5 rounded-2xl bg-white border border-stone-200 hover:border-ochre-gold flex items-center gap-3 transition-all shadow-xs cursor-pointer text-left" data-master-idx="1">')
    html.append('                <div class="w-12 h-12 rounded-xl overflow-hidden border-2 border-stone-200 group-hover:border-ochre-gold node-avatar-ring shrink-0">')
    html.append('                  <img src="imagenes/m_Da-Shifu-De-Yang-3.jpg" alt="Shi De Yang" class="w-full h-full object-cover">')
    html.append('                </div>')
    html.append('                <div>')
    html.append('                  <div class="text-xs font-bold text-stone-900 group-hover:text-primary transition-colors">Da Shifu Shi De Yang</div>')
    html.append('                  <div class="text-[11px] font-serif text-ochre-deep">释德扬 • Custodio del Linaje</div>')
    html.append('                </div>')
    html.append('                <span class="w-2 h-2 rounded-full bg-primary node-active-pill"></span>')
    html.append('              </button>')
    html.append('            </div>')
    html.append('')
    html.append('            <!-- Conector Ramificado hacia Nivel 3 (Shaolin Argentina) -->')
    html.append('            <div class="w-full max-w-lg flex flex-col items-center my-1">')
    html.append('              <div class="w-px h-6 bg-gradient-to-b from-primary to-ochre-gold"></div>')
    html.append('              <div class="w-3/5 h-px bg-stone-300 relative">')
    html.append('                <div class="absolute -top-1 left-0 w-2 h-2 rounded-full bg-primary"></div>')
    html.append('                <div class="absolute -top-1 right-0 w-2 h-2 rounded-full bg-primary"></div>')
    html.append('              </div>')
    html.append('              <div class="w-full flex justify-around gap-4 pt-2">')
    html.append('                <!-- Daniel Vera -->')
    html.append('                <div class="flex flex-col items-center">')
    html.append('                  <div class="text-[9px] font-bold uppercase tracking-widest text-primary mb-1">32ª Gen • Director</div>')
    html.append('                  <button type="button" class="tree-node-master group p-2.5 sm:p-3 rounded-2xl bg-white border border-stone-200 hover:border-primary flex items-center gap-2.5 transition-all shadow-xs cursor-pointer text-left" data-master-idx="2">')
    html.append('                    <div class="w-10 h-10 sm:w-11 sm:h-11 rounded-xl overflow-hidden border-2 border-stone-200 group-hover:border-primary node-avatar-ring shrink-0">')
    html.append('                      <img src="imagenes/m_Daniel-Vera-Shi-Xing-Wu-9.jpg" alt="Daniel Vera" class="w-full h-full object-cover">')
    html.append('                    </div>')
    html.append('                    <div>')
    html.append('                      <div class="text-xs font-bold text-stone-900 group-hover:text-primary transition-colors">Shifu Daniel Vera</div>')
    html.append('                      <div class="text-[10px] text-stone-500">Shi Xing Wu (释行午)</div>')
    html.append('                    </div>')
    html.append('                    <span class="w-2 h-2 rounded-full bg-primary node-active-pill"></span>')
    html.append('                  </button>')
    html.append('                </div>')
    html.append('                <!-- Yamila Melillo -->')
    html.append('                <div class="flex flex-col items-center">')
    html.append('                  <div class="text-[9px] font-bold uppercase tracking-widest text-primary mb-1">32ª Gen • Codirectora</div>')
    html.append('                  <button type="button" class="tree-node-master group p-2.5 sm:p-3 rounded-2xl bg-white border border-stone-200 hover:border-primary flex items-center gap-2.5 transition-all shadow-xs cursor-pointer text-left" data-master-idx="3">')
    html.append('                    <div class="w-10 h-10 sm:w-11 sm:h-11 rounded-xl overflow-hidden border-2 border-stone-200 group-hover:border-primary node-avatar-ring shrink-0">')
    html.append('                      <img src="imagenes/m_Shi-Xing-Gong-9.jpg" alt="Yamila Melillo" class="w-full h-full object-cover">')
    html.append('                    </div>')
    html.append('                    <div>')
    html.append('                      <div class="text-xs font-bold text-stone-900 group-hover:text-primary transition-colors">Shifu Yamila Melillo</div>')
    html.append('                      <div class="text-[10px] text-stone-500">Shi Xing Gong (释行宮)</div>')
    html.append('                    </div>')
    html.append('                    <span class="w-2 h-2 rounded-full bg-primary node-active-pill"></span>')
    html.append('                  </button>')
    html.append('                </div>')
    html.append('              </div>')
    html.append('            </div>')
    html.append('')
    html.append('            <!-- Conector Ramificado hacia Nivel 4 (Instructores & Sedes) -->')
    html.append('            <div class="w-full max-w-5xl flex flex-col items-center mt-3">')
    html.append('              <div class="w-px h-6 bg-gradient-to-b from-primary to-ochre-gold"></div>')
    html.append('              <div class="w-5/6 h-px bg-stone-300 relative">')
    html.append('                <div class="absolute -top-1 left-0 w-2 h-2 rounded-full bg-ochre-gold"></div>')
    html.append('                <div class="absolute -top-1 left-1/3 w-2 h-2 rounded-full bg-ochre-gold"></div>')
    html.append('                <div class="absolute -top-1 left-2/3 w-2 h-2 rounded-full bg-ochre-gold"></div>')
    html.append('                <div class="absolute -top-1 right-0 w-2.5 h-2.5 rounded-full bg-primary ring-2 ring-primary/30"></div>')
    html.append('              </div>')
    html.append('              <div class="w-full grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 pt-3">')
    html.append('                <!-- Miguel López -->')
    html.append('                <button type="button" class="tree-node-master group p-2.5 rounded-2xl bg-white border border-stone-200 hover:border-ochre-gold flex items-center gap-2.5 transition-all shadow-xs cursor-pointer text-left" data-master-idx="4">')
    html.append('                  <div class="w-10 h-10 rounded-xl overflow-hidden border border-stone-200 group-hover:border-ochre-gold node-avatar-ring shrink-0">')
    html.append('                    <img src="imagenes/m_Jiao-Lian-Miguel-Lopez-3.jpg" alt="Miguel López" class="w-full h-full object-cover">')
    html.append('                  </div>')
    html.append('                  <div class="min-w-0">')
    html.append('                    <div class="text-[10px] font-bold text-ochre-deep uppercase">Sede Akarma</div>')
    html.append('                    <div class="text-xs font-bold text-stone-900 group-hover:text-primary transition-colors truncate">Miguel López Márquez</div>')
    html.append('                  </div>')
    html.append('                  <span class="w-1.5 h-1.5 rounded-full bg-primary node-active-pill ml-auto"></span>')
    html.append('                </button>')
    html.append('')
    html.append('                <!-- Carlos Vighi -->')
    html.append('                <button type="button" class="tree-node-master group p-2.5 rounded-2xl bg-white border border-stone-200 hover:border-ochre-gold flex items-center gap-2.5 transition-all shadow-xs cursor-pointer text-left" data-master-idx="5">')
    html.append('                  <div class="w-10 h-10 rounded-xl overflow-hidden border border-stone-200 group-hover:border-ochre-gold node-avatar-ring shrink-0">')
    html.append('                    <img src="imagenes/m_Jiao-Lian-Carlos-Vighi-8.jpg" alt="Carlos Vighi" class="w-full h-full object-cover">')
    html.append('                  </div>')
    html.append('                  <div class="min-w-0">')
    html.append('                    <div class="text-[10px] font-bold text-ochre-deep uppercase">Sede Patio Sur</div>')
    html.append('                    <div class="text-xs font-bold text-stone-900 group-hover:text-primary transition-colors truncate">Carlos Vighi</div>')
    html.append('                  </div>')
    html.append('                  <span class="w-1.5 h-1.5 rounded-full bg-primary node-active-pill ml-auto"></span>')
    html.append('                </button>')
    html.append('')
    html.append('                <!-- Javier Cuberos -->')
    html.append('                <button type="button" class="tree-node-master group p-2.5 rounded-2xl bg-white border border-stone-200 hover:border-ochre-gold flex items-center gap-2.5 transition-all shadow-xs cursor-pointer text-left" data-master-idx="6">')
    html.append('                  <div class="w-10 h-10 rounded-xl overflow-hidden border border-stone-200 group-hover:border-ochre-gold node-avatar-ring shrink-0">')
    html.append('                    <img src="imagenes/m_Jiao-Lian-Javier-Cuberos-2.jpg" alt="Javier Cuberos" class="w-full h-full object-cover">')
    html.append('                  </div>')
    html.append('                  <div class="min-w-0">')
    html.append('                    <div class="text-[10px] font-bold text-ochre-deep uppercase">Sede Yang Tai</div>')
    html.append('                    <div class="text-xs font-bold text-stone-900 group-hover:text-primary transition-colors truncate">Javier Cuberos</div>')
    html.append('                  </div>')
    html.append('                  <span class="w-1.5 h-1.5 rounded-full bg-primary node-active-pill ml-auto"></span>')
    html.append('                </button>')
    html.append('')
    html.append('                <!-- Pablo Encinas (Sede Pechan) -->')
    html.append('                <button type="button" class="tree-node-master group p-2.5 rounded-2xl bg-amber-50/50 border-2 border-primary/40 hover:border-primary flex items-center gap-2.5 transition-all shadow-xs cursor-pointer text-left" data-master-idx="7">')
    html.append('                  <div class="w-10 h-10 rounded-xl overflow-hidden border-2 border-primary/50 group-hover:border-primary node-avatar-ring shrink-0">')
    html.append('                    <img src="imagenes/Pablo_Encinas.jpg" alt="Pablo Encinas" class="w-full h-full object-cover">')
    html.append('                  </div>')
    html.append('                  <div class="min-w-0">')
    html.append('                    <div class="text-[10px] font-bold text-primary uppercase flex items-center gap-1"><span class="w-1.5 h-1.5 rounded-full bg-primary"></span>Sede Pechan</div>')
    html.append('                    <div class="text-xs font-bold text-stone-900 group-hover:text-primary transition-colors truncate">Jiaolian Pablo Encinas</div>')
    html.append('                  </div>')
    html.append('                  <span class="w-2 h-2 rounded-full bg-primary node-active-pill ml-auto"></span>')
    html.append('                </button>')
    html.append('              </div>')
    html.append('            </div>')
    html.append('          </div>')
    html.append('        </div>')
    html.append('      </div>')
    html.append('')
    html.append('      <!-- 3. PANEL DINÁMICO DE DETALLE DEL MAESTRO (ACTIVO AL PASAR EL RATÓN O CLIC) -->')
    html.append('      <div id="master-profile-showcase" class="relative">')
    
    for idx, m in enumerate(masters_data):
        active_cls = "active" if idx == 0 else ""
        is_pechan = idx == 7
        border_cls = "border-2 border-primary/40 shadow-lg ring-1 ring-primary/20" if is_pechan else "border border-stone-200 shadow-md"
        bg_card = "bg-gradient-to-br from-amber-50/60 via-white to-amber-50/30" if is_pechan else "bg-white"
        
        html.append(f'        <!-- Ficha {m["index"]}: {m["name"]} -->')
        html.append(f'        <article id="{m["id"]}" class="master-profile-panel {active_cls} p-6 sm:p-10 rounded-3xl {bg_card} {border_cls} transition-all duration-300" data-panel-idx="{idx}">')
        html.append('          <div class="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">')
        
        # Columna Izquierda: Retrato y Sellos
        html.append('            <div class="lg:col-span-5 flex flex-col items-center text-center">')
        html.append('              <div class="relative w-56 h-56 sm:w-64 sm:h-64 md:w-72 md:h-72 rounded-3xl overflow-hidden bg-stone-100 border-2 border-stone-200/90 shadow-md ring-4 ring-amber-500/10">')
        html.append(f'                <img src="{m["photo"]}" alt="{m["name"]}" class="w-full h-full object-cover">')
        if m["chinese"]:
            html.append(f'                <div class="absolute bottom-2 right-2 px-2.5 py-1 rounded-lg bg-stone-950/80 backdrop-blur-xs text-ochre-gold font-serif text-sm border border-ochre-gold/30">{m["chinese"]}</div>')
        html.append('              </div>')
        html.append('              <div class="mt-4 flex flex-wrap items-center justify-center gap-2">')
        html.append(f'                <span class="px-3 py-1 rounded-full {m["badge_color"]} text-xs font-bold uppercase tracking-wider">{m["generation"]}</span>')
        html.append('              </div>')
        html.append('            </div>')
        
        # Columna Derecha: Información completa y viñetas
        html.append('            <div class="lg:col-span-7 space-y-4">')
        html.append('              <div>')
        html.append(f'                <div class="text-xs font-semibold uppercase tracking-wider text-ochre-deep mb-1">{m["role"]}</div>')
        html.append(f'                <h3 class="text-2xl sm:text-3xl font-extrabold font-display text-stone-900 tracking-tight">')
        html.append(f'                  {m["name"]}')
        if m["dates"]:
            html.append(f'                  <span class="text-sm font-normal text-stone-500 block sm:inline mt-0.5 sm:mt-0 font-sans">({m["dates"]})</span>')
        html.append('                </h3>')
        html.append('              </div>')
        
        # Descripción
        html.append(f'              <p class="text-stone-700 leading-relaxed text-sm sm:text-base font-body">{m["desc"]}</p>')
        
        # Puntos clave
        if m["points"]:
            html.append('              <div class="bg-stone-50/90 border border-stone-200/80 rounded-2xl p-4 sm:p-5 space-y-2 text-stone-700 text-xs sm:text-sm">')
            for p in m["points"]:
                icon = "stars" if "Discípulo" in p or "Líder" in p else "check_circle"
                color = "text-primary" if is_pechan else "text-ochre-deep"
                html.append(f'                <div class="flex items-start gap-2.5">')
                html.append(f'                  <span class="material-symbols-outlined {color} text-base shrink-0 mt-0.5">{icon}</span>')
                html.append(f'                  <span>{p}</span>')
                html.append(f'                </div>')
            html.append('              </div>')
            
        # Linaje Breadcrumb
        html.append('              <div class="pt-2 flex items-center gap-2 text-xs text-stone-500 font-medium border-t border-stone-100">')
        html.append('                <span class="material-symbols-outlined text-ochre-gold text-base shrink-0">lan</span>')
        html.append(f'                <span class="text-stone-700 font-semibold">{m["lineage"]}</span>')
        html.append('              </div>')
        
        # Botones de Acción si aplica
        if m.get("cta") or m.get("cta_wa"):
            html.append('              <div class="pt-3 flex flex-wrap items-center gap-3">')
            if m.get("cta"):
                cta = m["cta"]
                target = 'target="_blank" rel="noopener noreferrer"' if cta["url"].startswith("http") else ''
                html.append(f'                <a href="{cta["url"]}" {target} class="inline-flex items-center gap-1.5 px-5 py-2.5 rounded-xl bg-primary text-white text-xs font-bold uppercase tracking-wider hover:bg-primary-container shadow-xs transition-all">')
                html.append(f'                  <span>{cta["text"]}</span>')
                html.append(f'                  <span class="material-symbols-outlined text-sm">{cta["icon"]}</span>')
                html.append('                </a>')
            if m.get("cta_wa"):
                wa = m["cta_wa"]
                html.append(f'                <a href="{wa["url"]}" target="_blank" rel="noopener noreferrer" class="inline-flex items-center gap-1.5 px-5 py-2.5 rounded-xl bg-emerald-700 text-white text-xs font-bold uppercase tracking-wider hover:bg-emerald-800 shadow-xs transition-all">')
                html.append(f'                  <span>{wa["text"]}</span>')
                html.append(f'                  <span class="material-symbols-outlined text-sm">{wa["icon"]}</span>')
                html.append('                </a>')
            html.append('              </div>')
            
        html.append('            </div>')
        html.append('          </div>')
        html.append('        </article>')
        
    html.append('      </div>')
    html.append('    </section>')
    
    return "\n".join(html)

content = generate_html()
with open("scratch/arbol_component.html", "w", encoding="utf-8") as f:
    f.write(content)

print(f"Generated scratch/arbol_component.html ({len(content)} bytes)")
